# Generated by Django 3.0.3 on 2022-05-13 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
    ]
