# Generated by Django 3.0.3 on 2022-05-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_desc',
            field=models.TextField(null=True),
        ),
    ]
