# Generated by Django 3.0.3 on 2022-05-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_short_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Organization',
            new_name='Location',
        ),
        migrations.AddField(
            model_name='register',
            name='Proposed_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='Proposed_Time',
            field=models.TimeField(null=True),
        ),
    ]
