# Generated by Django 3.0.3 on 2022-05-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20220513_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Location',
            new_name='Organization',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Proposed_Date',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Proposed_Time',
        ),
    ]
