# Generated by Django 3.0.3 on 2022-05-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20220513_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Event_Date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Event_Location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Event_Time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Max_NO_Participants',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Meet_link',
        ),
        migrations.AddField(
            model_name='event',
            name='Phone_NO',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('dance', 'Dance'), ('music', 'Music'), ('arts', 'Arts'), ('crafts', 'Crafts'), ('learn', 'Learn')], max_length=200, null=True),
        ),
    ]
