# Generated by Django 3.0.3 on 2022-05-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20220513_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images/events')),
                ('photo_Desc', models.TextField(blank=True)),
            ],
        ),
    ]
